apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
spec:
  releaseName: vector
  chart:
    spec:
      chart: vector
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
      version: "0.25.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    role: "Agent"
    containerPorts:
      - name: prom-exporter
        containerPort: 9598
        protocol: TCP
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 400m
        memory: 512Mi