apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure/base/eck-operator
patches:
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: eck-operator-crds
        namespace: elasticsearch
      spec:
        patches:
          - patch: |-              
              - op: replace
                path: /spec/version
                value: 8.14.0
            target:
              group: elasticsearch.k8s.elastic.co
              version: v1
              kind: Elasticsearch
              name: log-storage

          - patch: |-              
              - op: replace
                path: /spec/version
                value: 8.14.0
            target:
              group: kibana.k8s.elastic.co
              version: v1
              kind: Kibana
              name: log-storage
        
              
